name: Crowdin Translation Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/main/generated/assets/galacticraft/lang/en_us.json'

jobs:
  crowdin_push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Crowdin Push
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false

          source: 'src/main/generated/assets/galacticraft/lang/en_us.json'
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}